apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: wp-wd
    tier: frontend
    track: stable
  name: wp-wd
  namespace: wp-wd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-wd
      name: wp-nginx
      tier: frontend
      track: stable
  strategy:
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wp-wd
        name: wp-nginx
        tier: frontend
        track: stable
    spec:
      containers:
      - env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.core.svc.cluster.local
        - name: WORDPRESS_DB_NAME
          value: dbWPWD
        - name: WORDPRESS_DB_USER
          value: wp-wd
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: mariadb-pass-wp-wd.txt
              name: mariadb-pass-wp-wd
        image: daxio/wordpress-redis-sock:v1.0.0
        imagePullPolicy: IfNotPresent
        name: wp
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-persistent-storage
        - mountPath: /usr/local/etc/php/conf.d
          name: php
        - mountPath: /var/run/nginx-cache
          name: cache
        - mountPath: /sock
          name: php-socket
      - image: daxio/nginx-naxsi:v1.1.4
        imagePullPolicy: IfNotPresent
        name: wp-nginx
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/www/html
          name: wp-persistent-storage
        - mountPath: /etc/nginx
          name: nginx
        - mountPath: /etc/nginx-conf/conf.d
          name: nginx-conf-d
        - mountPath: /etc/nginx-conf/global
          name: nginx-global
        - mountPath: /etc/nginx-conf/html
          name: nginx-html
        - mountPath: /var/run/nginx-cache
          name: cache
        - mountPath: /sock
          name: php-socket
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 33
      terminationGracePeriodSeconds: 30
      volumes:
      - name: wp-persistent-storage
        persistentVolumeClaim:
          claimName: wp-wd-pv-claim
      - configMap:
          defaultMode: 420
          name: php
        name: php
      - configMap:
          defaultMode: 420
          name: nginx
        name: nginx
      - configMap:
          defaultMode: 420
          name: nginx-conf-d
        name: nginx-conf-d
      - configMap:
          defaultMode: 420
          name: nginx-global
        name: nginx-global
      - configMap:
          defaultMode: 420
          name: nginx-html
        name: nginx-html
      - emptyDir:
          medium: Memory
        name: cache
      - emptyDir: {}
        name: php-socket
status: {}
